### ISSUE TITLE
Dio registracije, API

### ISSUE THREAD

**Issue by admirakeric** [cozyfirm/colors-app#5]
- Kreirati APIs koji će provjeravati ispravnost unešenog maila, username-a i šifre prilikom registracije;
- Kreirati APIs za uslove korištenja i verifikacije maila

**Comment by aladinkapic** [comment]
Dokumentacija za API-je za provjeru ispravnosti unesenih podataka dostupna [ovdje](https://github.com/cozyfirm/colors-app/blob/main/storage/documentation/auth/check.md).

Napomena: Nije spušteno na produkciju još

**Comment by admirakeric** [comment]
Ista stvar je i na login page-u:
- Kreirati APIs koji će provjeravati ispravnost unešenog maila i šifre prilikom logina

**Comment by aladinkapic** [comment]
Dodana i dokumentacija za Terms and conditions API:

https://github.com/cozyfirm/colors-app/tree/main/storage/documentation/open-api/info

**Comment by aladinkapic** [comment]
Dodana validacija email-a u commit-u "[Email validation;](https://github.com/cozyfirm/colors-app/commit/62f16c160fd54ffba3e4b3f0967097fd227471ca) https://github.com/cozyfirm/colors-app/issues/5"
