### ISSUE TITLE
Splash 

### ISSUE THREAD

**Issue by admirakeric** [cozyfirm/colors-app#6]
Kreirati API za sliku reklame koja se pojavljuje u dijelu Splash.

**Comment by aladinkapic** [comment]
Dodana opcija za GUI, da se mogu unositi splash screens od strane administratora:

![image](https://github.com/user-attachments/assets/509795db-0ad7-416d-a968-0d0fbbc034ea)

Ukoliko je dostupno više screen-ova, api će vraćati u random orderu screens

Dokumentacija za API se može pogledati [ovdje](https://github.com/cozyfirm/colors-app/blob/main/storage/documentation/open-api/config/splash-screen.md)
